// Generated by CoffeeScript 1.3.1
(function() {

  window.Collision = {};

  Collision.Util = (function() {

    Util.name = 'Util';

    function Util() {}

    Util.prototype.drawBall = function(ball, radius) {
      var context;
      context = document.getElementById("bounds").getContext('2d');
      context.beginPath();
      context.moveTo(ball.posX, ball.posY);
      context.arc(ball.posX, ball.posY, radius, 0, Math.PI * 2, false);
      context.closePath();
      context.fill();
      return context.stroke();
    };

    Util.prototype.clearCanvas = function() {
      var context;
      context = document.getElementById("bounds").getContext('2d');
      return context.clearRect(0, 0, context.canvas.width, context.canvas.height);
    };

    return Util;

  })();

}).call(this);
